### ISSUE TITLE
Conflict with other packages

### ISSUE THREAD

**Issue by Hellenophile** [thisisdhaas/moveproofs#3]
I get the following error while using the moveproofs package. 

theorem Error: Theorem style plain already defined.

(But I don't use the ntheorem package.) A screenshot is attached for reference. 
The document compiles smoothly without the moveprofs package. The document is set in the lipics-v2016 template.
![screen shot 2017-11-19 at 6 06 30 pm](https://user-images.githubusercontent.com/33810354/32993420-fc7d69c2-cd57-11e7-8c14-5bb0ef5e27e4.png)

**Comment by thisisdhaas** [comment]
Hm, I don't think I rely on the `ntheorem` package for anything, it must be an artifact of an older version. I'll get rid of it for you.
